In [1]:
import torch
import argparse
from model import MODEL
from run import train, test
import numpy as np
import torch.optim as optim
from dataloader import getDataLoader
from earlystop import EarlyStopping

In [2]:
gpu = 0
patience = 5
max_iter = 100  # number of iterations
init_lr = 0.005  # initial learning rate
lr_decay = 0.75  # learning rate decay
final_lr = 1E-5  # learning rate will not decrease after hitting this threshold
dropout = 0.3
exercise_embed_dim = 64  # hidden state dim for LSTM
hidden_dim = 64
layer_num = 2  # layer number for LSTM
max_step = 100  # the allowed maximum length of a sequence
maxgradnorm = 50.0  # maximum gradient norm
Lamda = 1  # hyper-parameter Lamda
alpha = 0.2  # alpha
num_heads = 4  # number of head attentions
mode = 3  # mode of integration function
# 1: ca / 2: mul / 3: ca mul / 4: rasch
fold = '1'  # number of fold
dataset = 'assist2009_B'

#when dataset is assist2009_B
batch_size = 32
n_knowledge_concept = 110  # the kinds of unique questions in the dataset
n_exercise = 16891  # the number of unique questions in the dataset
data_dir = './data/assist2009_B'  # data directory
data_name = 'assist2009_B'  # data set name

memory_size = n_knowledge_concept
lr = init_lr
memory_key_state_dim = exercise_embed_dim
memory_value_state_dim = exercise_embed_dim * 2

train_data_path = data_dir + "/" + data_name + "_train" + fold + ".csv"
valid_data_path = data_dir + "/" + data_name + "_valid" + fold + ".csv"
test_data_path = data_dir + "/" + data_name + "_test" + fold + ".csv"

In [3]:
import numpy as np
import itertools
class DataReader():
    def __init__(self, train_path, valid_path, test_path, maxstep, numofques):
        self.train_path = train_path
        self.valid_path = valid_path
        self.test_path = test_path
        self.maxstep = maxstep
        self.numofques = numofques

    def getTrainData(self):
        print('loading train data...')
        q_data= []
        qa_data =[]
        p_data= []
        trainData = []
        batch = 0
        with open(self.train_path, 'r') as train:
            for student, problem, ques, ans in itertools.zip_longest(*[train] * 4):
                batch = batch +1
                try:
                    problem = [int(p) for p in problem.strip().strip(',').split(',')]
                    ques = [int(q) for q in ques.strip().strip(',').split(',')]
                    ans = [int(a) for a in ans.strip().strip(',').split(',')]
                except:
                    print(batch)
                length = np.size(ques)
                slices = length//self.maxstep + (1 if length%self.maxstep > 0 else 0)
                for i in range(slices):
                    q_temp = np.zeros(shape=[self.maxstep])
                    qa_temp = np.zeros(shape=[self.maxstep])
                    p_temp = np.zeros(shape=[self.maxstep])
                    if length > 0:
                        if length >= self.maxstep:
                            l = self.maxstep
                        else:
                            l = length
                        for j in range(l):
                            q_temp[j] = ques[i*self.maxstep + j]
                            qa_temp[j] = ans[i*self.maxstep + j]
                            p_temp[j] = problem[i*self.maxstep + j]
                        length = length - self.maxstep
                    q_data.append(q_temp.tolist())
                    qa_data.append(qa_temp.tolist())
                    p_data.append(p_temp.tolist())
            print('train--question done: ' + str(np.array(q_data).shape))
            print('train--question_ans done: ' + str(np.array(qa_data).shape))
            print('train--problem done: ' + str(np.array(p_data).shape))
            return np.array(q_data).astype(float), np.array(qa_data).astype(float), np.array(p_data).astype(float)

    def getValidData(self):
        print('loading valid data...')
        q_data= []
        qa_data =[]
        p_data= []
        validData = []
        batch = 0
        with open(self.valid_path, 'r') as valid:
            for student, problem, ques, ans in itertools.zip_longest(*[valid] * 4):
                batch = batch +1
                try:
                    problem = [int(p) for p in problem.strip().strip(',').split(',')]
                    ques = [int(q) for q in ques.strip().strip(',').split(',')]
                    ans = [int(a) for a in ans.strip().strip(',').split(',')]
                except:
                    print(batch)
                length = np.size(ques)
                slices = length//self.maxstep + (1 if length%self.maxstep > 0 else 0)
                for i in range(slices):
                    q_temp = np.zeros(shape=[self.maxstep])
                    qa_temp = np.zeros(shape=[self.maxstep])
                    p_temp = np.zeros(shape=[self.maxstep])
                    if length > 0:
                        if length >= self.maxstep:
                            l = self.maxstep
                        else:
                            l = length
                        for j in range(l):
                            q_temp[j] = ques[i*self.maxstep + j]
                            qa_temp[j] = ans[i*self.maxstep + j]
                            p_temp[j] = problem[i*self.maxstep + j]
                        length = length - self.maxstep
                    q_data.append(q_temp.tolist())
                    qa_data.append(qa_temp.tolist())
                    p_data.append(p_temp.tolist())
            print('valid--question done: ' + str(np.array(q_data).shape))
            print('valid--question_ans done: ' + str(np.array(qa_data).shape))
            print('valid--problem done: ' + str(np.array(p_data).shape))
            return np.array(q_data).astype(float), np.array(qa_data).astype(float), np.array(p_data).astype(float)


    def getTestData(self):
        print('loading test data...')
        testData = []
        q_data = []
        qa_data = []
        p_data = []
        zero = [0 for i in range(self.numofques * 2)]
        batch = 0
        with open(self.test_path, 'r') as test:
            for student, problem, ques, ans in itertools.zip_longest(*[test] * 4):
                #length = int(length.strip().strip(','))
                batch = batch + 1
                try:
                    problem = [int(p) for p in problem.strip().strip(',').split(',')]
                    ques = [int(q) for q in ques.strip().strip(',').split(',')]
                    ans = [int(a) for a in ans.strip().strip(',').split(',')]
                except:
                    print(batch)
                length = np.size(ques)
                slices = length // self.maxstep + (1 if length % self.maxstep > 0 else 0)
                for i in range(slices):
                    q_temp = np.zeros(shape=[self.maxstep])
                    qa_temp = np.zeros(shape=[self.maxstep])
                    p_temp = np.zeros(shape=[self.maxstep])
                    if length > 0:
                        if length >= self.maxstep:
                            l = self.maxstep
                        else:
                            l = length
                        for j in range(l):
                            q_temp[j] = ques[i * self.maxstep + j]
                            qa_temp[j] = ans[i * self.maxstep + j]
                            p_temp[j] = problem[i * self.maxstep + j]
                        length = length - self.maxstep
                    q_data.append(q_temp.tolist())
                    qa_data.append(qa_temp.tolist())
                    p_data.append(p_temp.tolist())
            print('test--question done: ' + str(np.array(q_data).shape))
            print('test--question_ans done: ' + str(np.array(qa_data).shape))
            print('test--problem done: ' + str(np.array(p_data).shape))
            return np.array(q_data).astype(float), np.array(qa_data).astype(float), np.array(p_data).astype(float)



In [4]:
import sys
sys.path.append('/')
from readdata import DataReader
import numpy as np
from tqdm import tqdm


def getDataLoader(train_data_path, valid_data_path, test_data_path, max_step, n_knowledge_concept):
    handle = DataReader(train_data_path, valid_data_path, test_data_path, max_step, n_knowledge_concept)

    kc_data_train, respose_data_train, exercise_data_train = handle.getTrainData()
    kc_data_valid, respose_data_valid, exercise_data_valid = handle.getValidData()
    kc_data_test, respose_data_test, exercise_data_test = handle.getTestData()

    return kc_data_train, respose_data_train, exercise_data_train,kc_data_valid, respose_data_valid, exercise_data_valid, kc_data_test, respose_data_test, exercise_data_test



In [5]:
train_kc_data, train_respond_data, train_exercise_data, \
        valid_kc_data, valid_respose_data, valid_exercise_data, \
        test_kc_data, test_respose_data, test_exercise_data \
        = getDataLoader(train_data_path, valid_data_path, test_data_path, max_step, n_knowledge_concept)

loading train data...
train--question done: (3293, 100)
train--question_ans done: (3293, 100)
train--problem done: (3293, 100)
loading valid data...
valid--question done: (1038, 100)
valid--question_ans done: (1038, 100)
valid--problem done: (1038, 100)
loading test data...
test--question done: (1032, 100)
test--question_ans done: (1032, 100)
test--problem done: (1032, 100)


In [6]:
train_exercise_respond_data = train_respond_data * \
    n_exercise + train_exercise_data
valid_exercise_respose_data = valid_respose_data * \
    n_exercise + valid_exercise_data
test_exercise_respose_data = test_respose_data * \
    n_exercise + test_exercise_data
adj_exercise_kc = np.loadtxt(data_dir + "/exercise_kc_map.txt")


In [7]:
len(np.random.permutation(train_exercise_data.shape[0]))


3293

In [8]:
import torch
import torch.nn as nn
import numpy as np
import utils as utils
import embedd_loss as embedd_loss
from torch.autograd import Variable
import torch.nn.functional as F

In [9]:
n_exercise = n_exercise
n_kc = n_knowledge_concept
batch_size = batch_size
exercise_embed_dim = exercise_embed_dim
student_num = None
nheads = num_heads
alpha = alpha
dropout = dropout
# params = params
mode = mode
Lamda = Lamda
hidden_dim = hidden_dim
layer_num = layer_num

In [10]:
class Exercise_KC_GraphAttentionLayer(nn.Module):
    def __init__(self, in_features, out_features, dropout, alpha, mode, concat=True):
        super(Exercise_KC_GraphAttentionLayer, self).__init__()
        self.dropout = dropout
        self.in_features = in_features
        self.out_features = out_features
        self.alpha = alpha
        self.concat = concat
        self.mode =mode
        self.W1 = nn.Parameter(torch.empty(size=(in_features, out_features)))
        nn.init.kaiming_normal(self.W1)

        if mode == 1 or mode == 3:
            self.reduceDim = nn.Linear(in_features * 2, self.out_features, bias=True)
            nn.init.kaiming_normal(self.reduceDim.weight)
            nn.init.constant(self.reduceDim.bias, 0)
        if mode != 1:
            self.E = nn.Parameter(torch.empty(size=(in_features, out_features)))
            nn.init.kaiming_normal(self.E)
        if mode ==4:
            self.U = nn.Parameter(torch.empty(size=(in_features, 1)))
            nn.init.kaiming_normal(self.U)

        self.a = nn.Parameter(torch.empty(size=(2*out_features, 1)))
        nn.init.kaiming_normal(self.a)

        self.leakyrelu = nn.LeakyReLU(self.alpha)

    def forward(self, exercise_h, kc_h, adj_exercise_kc):
        if self.concat:
            kc_Wh = torch.mm(kc_h, self.W1)
            exercise_Wh = torch.mm(exercise_h, self.W1)
            a_input = self._prepare_attentional_mechanism_input(kc_Wh, exercise_Wh)
            e = self.leakyrelu(torch.matmul(a_input, self.a).squeeze(2))
            zero_vec = -9e15 * torch.ones_like(e)
            attention = torch.where(adj_exercise_kc > 0, e, zero_vec)
            attention = F.softmax(attention, dim=1)
            new_kc_embed = torch.matmul(attention, kc_Wh)

            if self.mode == 1:
                exercises_embedd = torch.cat((new_kc_embed, exercise_h), dim=1)
                exercises_embedd = self.reduceDim(exercises_embedd)
            if self.mode == 2:
                exercise_Eh = torch.mm(exercise_h, self.E)
                exercises_embedd = new_kc_embed.mul(exercise_Eh)
            if self.mode == 3:
                exercise_Eh = torch.mm(exercise_h, self.E)
                exercises_embedd = torch.cat((new_kc_embed, new_kc_embed.mul(exercise_Eh)), dim=1)
                exercises_embedd = self.reduceDim(exercises_embedd)
            if self.mode == 4:
                u = torch.mm(exercise_h, self.U)
                d_kt = torch.mm(new_kc_embed, self.E)
                exercises_embedd = new_kc_embed + u * d_kt
            return F.elu(exercises_embedd)

    def _prepare_attentional_mechanism_input(self, kc_Wh, exercise_Wh):
        N_kc = kc_Wh.size()[0]
        N_exercise = exercise_Wh.size()[0]
        Wh_repeated_in_chunks = exercise_Wh.repeat_interleave(N_kc, dim=0)
        Wh_repeated_alternating = kc_Wh.repeat(N_exercise, 1)
        all_combinations_matrix = torch.cat([Wh_repeated_in_chunks, Wh_repeated_alternating], dim=1)
        return all_combinations_matrix.view(N_exercise, N_kc, 2 * self.out_features)

    def __repr__(self):
        return self.__class__.__name__ + ' (' + str(self.in_features) + ' -> ' + str(self.out_features) + ')'

In [11]:
lstm = nn.LSTM(exercise_embed_dim * 2, hidden_dim,
               layer_num, batch_first=True, dropout=dropout)
fc1 = nn.Linear(exercise_embed_dim + hidden_dim, hidden_dim, bias=True)
fc2 = nn.Linear(hidden_dim, 1, bias=True)
rel = nn.ReLU()

exercise_embed = nn.Parameter(torch.randn(n_exercise, exercise_embed_dim))
kc_embed = nn.Parameter(torch.randn(n_kc, exercise_embed_dim))



In [12]:
dropout = dropout
in_features = exercise_embed_dim
out_features = exercise_embed_dim
alpha = alpha
concat = True
mode = mode
W1 = nn.Parameter(torch.empty(size=(in_features, out_features)))
nn.init.kaiming_normal(W1)

/tmp/ipykernel_650/995484167.py:8: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(W1)


Parameter containing:
tensor([[-0.1825, -0.0280,  0.1855,  ..., -0.3000,  0.2146, -0.0690],
        [-0.0536, -0.2473, -0.2712,  ...,  0.0443,  0.2027, -0.0449],
        [ 0.0055,  0.0771,  0.1112,  ...,  0.3770,  0.0359, -0.1277],
        ...,
        [-0.0626, -0.1749, -0.1026,  ..., -0.1415, -0.3213,  0.2746],
        [ 0.1376,  0.0135, -0.3266,  ..., -0.0584,  0.2207,  0.0710],
        [ 0.0377, -0.0575,  0.0066,  ..., -0.1305, -0.0184, -0.1846]],
       requires_grad=True)

In [13]:
reduceDim = nn.Linear(in_features * 2, out_features, bias=True)
nn.init.kaiming_normal(reduceDim.weight)
nn.init.constant(reduceDim.bias, 0)

E = nn.Parameter(torch.empty(size=(in_features, out_features)))
nn.init.kaiming_normal(E)

U = nn.Parameter(torch.empty(size=(in_features, 1)))
nn.init.kaiming_normal(U)

a = nn.Parameter(torch.empty(size=(2*out_features, 1)))
nn.init.kaiming_normal(a)

leakyrelu = nn.LeakyReLU(alpha)

/tmp/ipykernel_650/1761267380.py:2: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(reduceDim.weight)
/tmp/ipykernel_650/1761267380.py:3: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(reduceDim.bias, 0)
/tmp/ipykernel_650/1761267380.py:6: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(E)
/tmp/ipykernel_650/1761267380.py:9: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(U)
/tmp/ipykernel_650/1761267380.py:12: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(a)


In [14]:
exercise_embed.shape

torch.Size([16891, 64])

In [15]:
def _prepare_attentional_mechanism_input(kc_Wh, exercise_Wh):
    N_kc = kc_Wh.size()[0]
    N_exercise = exercise_Wh.size()[0]
    Wh_repeated_in_chunks = exercise_Wh.repeat_interleave(N_kc, dim=0)
    Wh_repeated_alternating = kc_Wh.repeat(N_exercise, 1)
    all_combinations_matrix = torch.cat(
        [Wh_repeated_in_chunks, Wh_repeated_alternating], dim=1)
    return all_combinations_matrix.view(N_exercise, N_kc, 2 * self.out_features)


In [45]:
kc_one_seq = train_respond_data[0:32, :]
exercise_one_seq = train_exercise_data[0:32, :]
exercise_respond_batch_seq = train_exercise_respond_data[0:32, :]
target = train_exercise_respond_data[0:32, :]
target = (target - 1) / n_exercise
target = np.floor(target)
input_kc = utils.varible(torch.LongTensor(kc_one_seq), gpu)
input_exercise = utils.varible(torch.LongTensor(exercise_one_seq), gpu)
input_exercise_respond = utils.varible(
    torch.LongTensor(exercise_respond_batch_seq), gpu)
target = utils.varible(torch.FloatTensor(target), gpu)
target.shape
target = target[:, 1:]
target.shape

torch.Size([32, 99])

In [68]:
a = torch.tensor(np.random.randint(5, size = (3,4)))
print(a)
b = a.repeat_interleave(3, dim=0)
print(b)
c = a.repeat_interleave(3, dim=1)
print(c)
d = a.repeat(3,1)
print(d)
e = torch.cat([a, b], dim=0)
print(e)
f = torch.cat([a, c], dim=1)
print(f)

tensor([[3, 2, 1, 0],
        [0, 4, 2, 0],
        [2, 0, 4, 0]])
tensor([[3, 2, 1, 0],
        [3, 2, 1, 0],
        [3, 2, 1, 0],
        [0, 4, 2, 0],
        [0, 4, 2, 0],
        [0, 4, 2, 0],
        [2, 0, 4, 0],
        [2, 0, 4, 0],
        [2, 0, 4, 0]])
tensor([[3, 3, 3, 2, 2, 2, 1, 1, 1, 0, 0, 0],
        [0, 0, 0, 4, 4, 4, 2, 2, 2, 0, 0, 0],
        [2, 2, 2, 0, 0, 0, 4, 4, 4, 0, 0, 0]])
tensor([[3, 2, 1, 0],
        [0, 4, 2, 0],
        [2, 0, 4, 0],
        [3, 2, 1, 0],
        [0, 4, 2, 0],
        [2, 0, 4, 0],
        [3, 2, 1, 0],
        [0, 4, 2, 0],
        [2, 0, 4, 0]])
tensor([[3, 2, 1, 0],
        [0, 4, 2, 0],
        [2, 0, 4, 0],
        [3, 2, 1, 0],
        [3, 2, 1, 0],
        [3, 2, 1, 0],
        [0, 4, 2, 0],
        [0, 4, 2, 0],
        [0, 4, 2, 0],
        [2, 0, 4, 0],
        [2, 0, 4, 0],
        [2, 0, 4, 0]])
tensor([[3, 2, 1, 0, 3, 3, 3, 2, 2, 2, 1, 1, 1, 0, 0, 0],
        [0, 4, 2, 0, 0, 0, 0, 4, 4, 4, 2, 2, 2, 0, 0, 0],
        [2, 0, 

In [101]:
exercise_embed = nn.Parameter(torch.randn(self.n_exercise, self.exercise_embed_dim))

NameError: name 'self' is not defined

In [76]:
kc_embed.shape
exercise_embed.shape
kc_Wh = torch.mm(kc_embed, W1)
exercise_Wh = torch.mm(exercise_embed, W1)
N_kc = kc_Wh.size()[0]
N_exercise = exercise_Wh.size()[0]
Wh_repeated_in_chunks = exercise_Wh.repeat_interleave(N_kc, dim=0)
# 110개의 knowledge_concept에 대해 문항별 weight 생성
Wh_repeated_alternating = kc_Wh.repeat(N_exercise, 1)
# 16891개의 exercise에 대해 kc별 weight 생성
all_combinations_matrix = torch.cat(
    [Wh_repeated_in_chunks, Wh_repeated_alternating], dim=1)
a_input = all_combinations_matrix


In [73]:
print(Wh_repeated_alternating.shape)
print(Wh_repeated_in_chunks.shape)

torch.Size([1858010, 64])
torch.Size([1858010, 64])


In [79]:
a = nn.Parameter(torch.empty(size=(2*64, 1)))
nn.init.kaiming_normal(a)
a.shape

/tmp/ipykernel_650/2829987827.py:2: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(a)


torch.Size([128, 1])

In [100]:
16891*110

1858010

In [93]:
e = leakyrelu(torch.matmul(a_input, a).squeeze(1))
zero_vec = -9e15 * torch.ones_like(e)
adj_exercise_kc = utils.varible(torch.from_numpy(adj_exercise_kc), gpu)
attention = torch.where(adj_exercise_kc > 0, e, zero_vec)
attention = F.softmax(attention, dim=1)
new_kc_embed = torch.matmul(attention, kc_Wh)


RuntimeError: Expected condition, x and y to be on the same device, but condition is on cuda:0 and x and y are on cpu and cpu respectively

In [17]:
exercise_Wh.repeat_interleave(110, dim=0).shape
# 110개의 knowledge_concept에 대해 문항별 weight 생성
kc_Wh.repeat(16891, 1).shape
# 16891개의 exercise에 대해 

NameError: name 'exercise_Wh' is not defined

In [ ]:
# Exercise_KC_GraphAttentionLayer(self.exercise_embed_dim, self.exercise_embed_dim, dropout=self.dropout, alpha=self.alpha, mode=self.mode,
# concat=True) for _ in range(self.nheads)]
kc_h = kc_embed
exercise_h = exercise_embed
kc_Wh = torch.mm(kc_h, W1) #(110, 64)
exercise_Wh = torch.mm(exercise_h, W1) #(16891, 64)
